### ISSUE TITLE
我遇到了这个错误

### ISSUE THREAD

**Issue by fredxie07** [Veminem/vuepress-theme-oneN#9]
Module not found: Error: Can't resolve '@SearchBox' in 'E:\coding\vuepress\vuepress-blog\node_modules\vuepress-theme-onen\components'

**Comment by fredxie07** [comment]
我看了一下  目前没有SearchBox这个组件 但是引用了SearchBox这个组件 导致的报错

**Comment by Wiensss** [comment]
> 我看了一下目前没有SearchBox这个组件但是引用了SearchBox这个组件导致的报错

SearchBox 是官方的内置组件，主题里是以插件的形式引入的，具体位置在配置文件下 [index.js](https://github.com/Veminem/vuepress-theme-oneN/blob/master/index.js)：
```js
[
      '@vuepress/search',
      { searchMaxSuggestions: 5 }
 ]
```
一般不主动删减默认配置文件不会出错。
也参考下官方文档关于插件的配置使用 [插件](https://vuepress.vuejs.org/zh/plugin/#%E6%8F%92%E4%BB%B6)

**Comment by fredxie07** [comment]
好 已经解决了 谢谢你
